/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manajemen_Surat.Frame;

import Manajemen_Surat.Kelas.Bagian;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aziz
 */
public class MenuLogBagian extends javax.swing.JPanel {

    /**
     * Creates new form MenuLogBagian
     */
    public MenuLogBagian() throws ParseException {
        initComponents();
        loadTabel();
    }

    public void loadTabel() throws ParseException {

       
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        model.addColumn("User Login");
        model.addColumn("Kolom yang berubah");
        model.addColumn("Nilai lama");
        model.addColumn("Nilai baru");
        model.addColumn("Waktu");
        model.addColumn("Keterangan");

        try {
            Bagian k = new Bagian();
            ResultSet data = k.KodeTampilTabelLog();

            
            SimpleDateFormat originalFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy", new Locale("id", "ID"));

            while (data.next()) {
                String waktu = data.getString("waktu"); 
                String waktuFormatted = "";
                if (waktu != null) {
                    waktuFormatted = timeFormat.format(originalFormat.parse(waktu)) + "\n"
                            + dateFormat.format(originalFormat.parse(waktu));
                }

                model.addRow(new Object[]{
                    data.getString("user_login"),
                    data.getString("kolom_yang_berubah"),
                    data.getString("nilai_lama"),
                    data.getString("nilai_baru"),
                    waktuFormatted, 
                    data.getString("keterangan"),});
            }

            data.close();
        } catch (SQLException sQLException) {
            sQLException.printStackTrace(); 
        }

        tb_LogBagian.setModel(model);

        
        tb_LogBagian.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                JTextArea textArea = new JTextArea(value != null ? value.toString() : "");
                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true); 
                textArea.setOpaque(true); 
                if (isSelected) {
                    textArea.setBackground(table.getSelectionBackground());
                    textArea.setForeground(table.getSelectionForeground());
                } else {
                    textArea.setBackground(table.getBackground());
                    textArea.setForeground(table.getForeground());
                }
                return textArea;
            }
        });

       
        tb_LogBagian.setRowHeight(40);


        tb_LogBagian.getColumnModel().getColumn(0).setPreferredWidth(90); 
        tb_LogBagian.getColumnModel().getColumn(1).setPreferredWidth(90); 
        tb_LogBagian.getColumnModel().getColumn(2).setPreferredWidth(130); 
        tb_LogBagian.getColumnModel().getColumn(3).setPreferredWidth(130); 
        tb_LogBagian.getColumnModel().getColumn(4).setPreferredWidth(90); 
        tb_LogBagian.getColumnModel().getColumn(5).setPreferredWidth(240); 

        
        tb_LogBagian.getTableHeader().setReorderingAllowed(false); 
        tb_LogBagian.getTableHeader().setResizingAllowed(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_LogBagian = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Menu Log Bagian");

        tb_LogBagian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_LogBagian);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 928, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_LogBagian;
    // End of variables declaration//GEN-END:variables
}
