/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Perpustakaan.FRAME;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Perpustakaan.KELAS.Item;
import Perpustakaan.popUp.PopUp_Item;
import Perpustakaan.popUp.PopUp_Item1;

/**
 *
 * @author WINDOWS 10
 */
public class menuItem extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public menuItem() {
        initComponents();
        loadTable();
    }
    
     private void loadTable() {
        // Inisialisasi model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Item");
        model.addColumn("Kategori");
        model.addColumn("Lemari");
        model.addColumn("Judul");
        model.addColumn("Penulis");
        model.addColumn("Tahun Terbit");
        model.addColumn("Jumlah");
        model.addColumn("File");

        try {
            Item itemHandler = new Item();
            ResultSet resultSet = itemHandler.tampilItem();

            // Iterasi hasil query dan tambahkan ke model tabel
            while (resultSet.next()) {
                model.addRow(new Object[] {
                    resultSet.getInt("id_item"),
                    resultSet.getString("nama_kategori"),
                    resultSet.getString("lemari"),
                    resultSet.getString("nama_barang"),
                    resultSet.getString("penulis"),
                    resultSet.getInt("tahun_terbit"),
                    resultSet.getInt("jumlah"),
                    resultSet.getString("file")
                });
            }
        } catch (SQLException e) {
            Logger.getLogger(menuItem.class.getName()).log(Level.SEVERE, "Error loading table data", e);
        }

        // Set model ke tabel
        tItem.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tItem = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 125, 197));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/add.png"))); // NOI18N
        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tItem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            PopUp_Item pp = new PopUp_Item();
            pp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tItemMouseClicked
        // TODO add your handling code here:
        try {
            int selectedRow = tItem.rowAtPoint(evt.getPoint());

            // Mengambil data dari tabel dengan pemeriksaan null
            String idItem = tItem.getValueAt(selectedRow, 0).toString();
            String kategori = tItem.getValueAt(selectedRow, 1).toString();
            String lemari = tItem.getValueAt(selectedRow, 2).toString();
            String namaBarang = tItem.getValueAt(selectedRow, 3).toString();
            String penulis = tItem.getValueAt(selectedRow, 4).toString();
            String tahunTerbit = tItem.getValueAt(selectedRow, 5).toString();
            String jumlah = tItem.getValueAt(selectedRow, 6).toString();

            // Membuka PopUp_Item1
            PopUp_Item1 popup = new PopUp_Item1();
            popup.Lb_item.setText(idItem);
            popup.cKategori.setSelectedItem(kategori);
            popup.tLemari.setText(lemari);
            popup.tNamaBarang.setText(namaBarang);
            popup.tPenulis.setText(penulis);
            popup.tTahunTerbit.setText(tahunTerbit);
            popup.tJumlah.setText(jumlah);
            popup.setVisible(true);

        } catch (SQLException e) {
            Logger.getLogger(menuItem.class.getName()).log(Level.SEVERE, "Error handling table click", e);
        }
    }//GEN-LAST:event_tItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tItem;
    // End of variables declaration//GEN-END:variables

}
