/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Perpustakaan.FRAME;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Perpustakaan.KELAS.Anggota;
import Perpustakaan.popUp.PopUp_Anggota;
import Perpustakaan.popUp.PopUp_Dosen;
import Perpustakaan.popUp.PopUp_Masyarakat;
import Perpustakaan.popUp.popUp_AngUBAH;
import Perpustakaan.popUp.popUp_DOSENUBAH;
import Perpustakaan.popUp.popUp_UMUM;

/**
 *
 * @author WINDOWS 10
 */
public class menuAnggota extends javax.swing.JPanel {

    private int baris;

    /**
     * Creates new form Dashboard
     */
    public menuAnggota() {
        initComponents();
        loadTableMahasiswa();
    }
    
    
     void loadTableMahasiswa() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id_Anggota");
        model.addColumn("nama");
        model.addColumn("alamat");
        model.addColumn("nohp");
        model.addColumn("email");
        model.addColumn("nim");
        model.addColumn("nidm");
        model.addColumn("nik");

        try {
            Anggota pj = new Anggota();
            ResultSet data = pj.tampilAnggota();
            while (data.next()) {
                model.addRow(new Object[]{
                    data.getInt("id_anggota"),
                    data.getString("nama"),
                    data.getString("alamat"),
                    data.getString("nohp"),
                    data.getString("email"),
                    data.getString("nim"),
                    data.getString("nidm"),
                    data.getString("nik"),
                });
            }
            tAnggotaMahasiswa.setModel(model);
        } catch (SQLException sQLException) {
            Logger.getLogger(menuAnggota.class.getName()).log(Level.SEVERE, null, sQLException);
        }
    }
    
    // Tambahan metode lainnya tetap sama
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bTambahMAHASISWA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAnggotaMahasiswa = new javax.swing.JTable();
        bTambahDOSEN = new javax.swing.JButton();
        bTambahDOSEN1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 125, 197));

        bTambahMAHASISWA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bTambahMAHASISWA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/add.png"))); // NOI18N
        bTambahMAHASISWA.setText("MAHASISWA");
        bTambahMAHASISWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahMAHASISWAActionPerformed(evt);
            }
        });

        tAnggotaMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tAnggotaMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAnggotaMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tAnggotaMahasiswa);

        bTambahDOSEN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bTambahDOSEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/add.png"))); // NOI18N
        bTambahDOSEN.setText("DOSEN");
        bTambahDOSEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahDOSENActionPerformed(evt);
            }
        });

        bTambahDOSEN1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bTambahDOSEN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/add.png"))); // NOI18N
        bTambahDOSEN1.setText("UMUM");
        bTambahDOSEN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahDOSEN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bTambahMAHASISWA)
                        .addGap(19, 19, 19)
                        .addComponent(bTambahDOSEN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(bTambahDOSEN1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambahMAHASISWA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTambahDOSEN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTambahDOSEN1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahMAHASISWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahMAHASISWAActionPerformed
         try {
            PopUp_Anggota pp = new PopUp_Anggota();
            pp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bTambahMAHASISWAActionPerformed

    private void tAnggotaMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tAnggotaMahasiswaMouseClicked
        baris = tAnggotaMahasiswa.getSelectedRow();

        String id_Anggota = tAnggotaMahasiswa.getValueAt(baris, 0).toString();
        String nama = tAnggotaMahasiswa.getValueAt(baris, 1).toString();
        String alamat = tAnggotaMahasiswa.getValueAt(baris, 2).toString();
        String nohp = tAnggotaMahasiswa.getValueAt(baris, 3).toString();
        String email = tAnggotaMahasiswa.getValueAt(baris, 4).toString();
        String nim = tAnggotaMahasiswa.getValueAt(baris, 5) != null ? tAnggotaMahasiswa.getValueAt(baris, 5).toString() : "";
        String nidm = tAnggotaMahasiswa.getValueAt(baris, 6) != null ? tAnggotaMahasiswa.getValueAt(baris, 6).toString() : "";
        String nik = tAnggotaMahasiswa.getValueAt(baris, 7) != null ? tAnggotaMahasiswa.getValueAt(baris, 7).toString() : "";

        try {
            if (!nim.isEmpty()) {
                popUp_AngUBAH anggotaEdit = new popUp_AngUBAH();
                anggotaEdit.lb_Id.setText(id_Anggota);
                anggotaEdit.tNama.setText(nama);
                anggotaEdit.tAlamat.setText(alamat);
                anggotaEdit.tNoHp.setText(nohp);
                anggotaEdit.tEmail.setText(email);
                anggotaEdit.tNim.setText(nim);
                anggotaEdit.setVisible(true);
            } else if (!nidm.isEmpty()) {
                popUp_DOSENUBAH dosenEdit = new popUp_DOSENUBAH();
                dosenEdit.lb_dosen.setText(id_Anggota);
                dosenEdit.tNama.setText(nama);
                dosenEdit.tAlamat.setText(alamat);
                dosenEdit.tNoHp.setText(nohp);
                dosenEdit.tEmail.setText(email);
                dosenEdit.tNidm.setText(nidm);
                dosenEdit.setVisible(true);
            } else if (!nik.isEmpty()) {
                popUp_UMUM umumEdit = new popUp_UMUM();
                umumEdit.lb_umum.setText(id_Anggota);
                umumEdit.tNama.setText(nama);
                umumEdit.tAlamat.setText(alamat);
                umumEdit.tNoHp.setText(nohp);
                umumEdit.tEmail.setText(email);
                umumEdit.tNik.setText(nik);
                umumEdit.setVisible(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(menuAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tAnggotaMahasiswaMouseClicked

    private void bTambahDOSENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahDOSENActionPerformed
        // TODO add your handling code here:     
        try {
            PopUp_Dosen pp = new PopUp_Dosen();
            pp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bTambahDOSENActionPerformed

    private void bTambahDOSEN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahDOSEN1ActionPerformed
        // TODO add your handling code here:
        try {
            PopUp_Masyarakat pm = new PopUp_Masyarakat();
            pm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bTambahDOSEN1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTambahDOSEN;
    private javax.swing.JButton bTambahDOSEN1;
    private javax.swing.JButton bTambahMAHASISWA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tAnggotaMahasiswa;
    // End of variables declaration//GEN-END:variables
 
}
