/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pembayaran.template;

import Pembayaran.Kelas.Pembayaran;
import Pembayaran.Kelas.jenis_pembayaran;
import Pembayaran.Kelas.mahasiswa;
import Pembayaran.Kelas.pb_sementara;
import Pembayaran.popUp.PopMahasiswa;
import Pembayaran.popUp.TambahJenis2;
import static Pembayaran.template.Main.pnKonten;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Alxxstrdy
 */
public class pnPembayaran extends javax.swing.JPanel {

    /**
     * Creates new form pnHome
     */
    public pnPembayaran() {
        initComponents();
        getData();
        AutoCompleteDecorator.decorate(cJenis);
        cJenis();
        peringatan.setVisible(false);
        autoID();
        bBayar.setVisible(false);
        bBayCetk.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPembayaran = new javax.swing.JTable();
        bTambahJenis = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bBayar = new javax.swing.JButton();
        bBayCetk = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        cJenis = new javax.swing.JComboBox<>();
        lblHarga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNomBay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cBayar = new javax.swing.JComboBox<>();
        peringatan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tKeterangan = new javax.swing.JTextField();
        tID = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnKuitansi = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tNama1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tProdi = new javax.swing.JLabel();
        tAngkatan = new javax.swing.JLabel();
        tNim = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tNamJen = new javax.swing.JLabel();
        tJumlah = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tTanggal = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tKeterangann = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tNama2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tProdi2 = new javax.swing.JLabel();
        tAngkatan2 = new javax.swing.JLabel();
        tNim2 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tNamJen2 = new javax.swing.JLabel();
        tJumlah2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        tTanggal2 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(173, 217, 216));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        tbPembayaran.setFont(new java.awt.Font("DM Sans 18pt Medium", 0, 12)); // NOI18N
        tbPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPembayaran);

        bTambahJenis.setBackground(new java.awt.Color(173, 217, 216));
        bTambahJenis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bTambahJenis.setText("+");
        bTambahJenis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTambahJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahJenisActionPerformed(evt);
            }
        });

        bTambah.setBackground(new java.awt.Color(173, 217, 216));
        bTambah.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 12)); // NOI18N
        bTambah.setText("TAMBAH MAHASISWA");
        bTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bBayar.setBackground(new java.awt.Color(38, 222, 129));
        bBayar.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 12)); // NOI18N
        bBayar.setText("Bayar");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });

        bBayCetk.setBackground(new java.awt.Color(38, 222, 129));
        bBayCetk.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 12)); // NOI18N
        bBayCetk.setText("Bayar + Cetak");
        bBayCetk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayCetkActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(252, 92, 101));
        bReset.setFont(new java.awt.Font("DM Sans 18pt Medium", 0, 12)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("RESET");
        bReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        cJenis.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 12)); // NOI18N
        cJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jenis -" }));
        cJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJenisActionPerformed(evt);
            }
        });

        lblHarga.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 24)); // NOI18N
        lblHarga.setText("Rp.0");

        jLabel2.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 24)); // NOI18N
        jLabel2.setText("Rp.");

        tNomBay.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 14)); // NOI18N
        tNomBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomBayActionPerformed(evt);
            }
        });
        tNomBay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNomBayKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DM Sans 24pt Medium", 0, 12)); // NOI18N
        jLabel1.setText("Nominal Pembayaran");

        jLabel3.setFont(new java.awt.Font("DM Sans 18pt Medium", 0, 12)); // NOI18N
        jLabel3.setText("Nominal Dibayar");

        jLabel4.setFont(new java.awt.Font("DM Sans 18pt Medium", 0, 12)); // NOI18N
        jLabel4.setText("Pilih Pembayaran Secara :");

        cBayar.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 12)); // NOI18N
        cBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH -", "LUNAS", "CICIL" }));
        cBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBayarActionPerformed(evt);
            }
        });

        peringatan.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 12)); // NOI18N
        peringatan.setForeground(new java.awt.Color(204, 0, 0));
        peringatan.setText("Nominal Bayar Lebih!");

        jLabel5.setFont(new java.awt.Font("DM Sans 18pt Medium", 0, 14)); // NOI18N
        jLabel5.setText("Keterangan");

        tKeterangan.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 12)); // NOI18N

        tID.setFont(new java.awt.Font("DM Sans 18pt SemiBold", 0, 14)); // NOI18N
        tID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tID.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bBayCetk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bTambahJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(275, 275, 275))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(peringatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tNomBay))
                                        .addGap(68, 68, 68))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cBayar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tKeterangan))
                        .addGap(351, 351, 351))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bTambahJenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cJenis))
                    .addComponent(tID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tKeterangan)
                    .addComponent(lblHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(tNomBay, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(peringatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBayCetk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        pnKuitansi.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INSTITUT TEKNOLOGI MOJOSARI");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Alamat : Jl Wachid Hasyim, Mojosari Ngepeh, Kec. Loceret, Kab Nganjuk Jawa Timur 64471");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Website : www.itmnganjuk.ac.id / Email. admin@itmnganjuk.ac.id");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Nama:");

        tNama1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tNama1.setText("Nama");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Prodi :");

        tProdi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tProdi.setText("Pendidikan Teknologi Informasi");

        tAngkatan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tAngkatan.setText("Nama");

        tNim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tNim.setText("Nama");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("NIM :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Angkatan");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("UNTUK PEMBAYARAN");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("SLIP BUKTI PEMBAYARAN");

        tNamJen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tNamJen.setText("jLabel19");

        tJumlah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tJumlah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tJumlah.setText("jLabel19");

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        tTanggal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tTanggal.setText("00=00=0000");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Nganjuk,");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Bendahara");

        jLabel24.setText("(....................................)");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Keterangan :");

        tKeterangann.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tKeterangann.setText("jLabel26");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tNama1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(tNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(tNamJen, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(tJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tKeterangann, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(0, 0, 0)
                                        .addComponent(tTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tProdi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tAngkatan)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tNama1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tNim))))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNamJen)
                    .addComponent(tJumlah))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTanggal)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(tKeterangann))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("INSTITUT TEKNOLOGI MOJOSARI");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Alamat : Jl Wachid Hasyim, Mojosari Ngepeh, Kec. Loceret, Kab Nganjuk Jawa Timur 64471");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Website : www.itmnganjuk.ac.id / Email. admin@itmnganjuk.ac.id");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setText("Nama:");

        tNama2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tNama2.setText("Nama");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setText("Prodi :");

        tProdi2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tProdi2.setText("Pendidikan Teknologi Informasi");

        tAngkatan2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tAngkatan2.setText("Nama");

        tNim2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tNim2.setText("Nama");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setText("NIM :");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel37.setText("Angkatan");

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("UNTUK PEMBAYARAN");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("SLIP BUKTI PEMBAYARAN");

        tNamJen2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tNamJen2.setText("jLabel19");

        tJumlah2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tJumlah2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tJumlah2.setText("jLabel19");

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        tTanggal2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tTanggal2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tTanggal2.setText("00=00=0000");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("Nganjuk,");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Bendahara");

        jLabel45.setText("(....................................)");

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel46.setText("Keterangan :");

        jLabel50.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel50.setText("jLabel26");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tNim2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tAngkatan2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tProdi2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(tNamJen2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tJumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(0, 0, 0)
                                        .addComponent(tTanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addGap(0, 0, 0)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(tProdi2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(tAngkatan2)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tNama2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(tNim2))))
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNamJen2)
                    .addComponent(tJumlah2))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTanggal2)
                    .addComponent(jLabel43)
                    .addComponent(jLabel46)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnKuitansiLayout = new javax.swing.GroupLayout(pnKuitansi);
        pnKuitansi.setLayout(pnKuitansiLayout);
        pnKuitansiLayout.setHorizontalGroup(
            pnKuitansiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnKuitansiLayout.setVerticalGroup(
            pnKuitansiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKuitansiLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(pnKuitansi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(829, 829, 829)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        add(jPanel3, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void cBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBayarActionPerformed

        if (cBayar.getSelectedItem().equals("LUNAS")) {
            tNomBay.setText(lblHarga.getText().substring(3));
            bBayar.setVisible(true);
            bBayCetk.setVisible(true);
        } else if (cBayar.getSelectedItem().equals("CICIL")) {
            if (cBayar.getSelectedItem().equals("- PILIH -")) {
                JOptionPane.showMessageDialog(null, "NOMINAL BAYAR BELUM DIISI");
                cBayar.setSelectedIndex(0);
                bBayar.setVisible(false);
                bBayCetk.setVisible(false);
            } else {
                int bayar = Integer.parseInt(tNomBay.getText().replace(".", ""));
                int harga = Integer.parseInt(lblHarga.getText().replace(".", "").substring(2));
                bBayar.setVisible(true);
                bBayCetk.setVisible(true);
                if (bayar == harga) {
                    JOptionPane.showMessageDialog(null, "NOMINAL BAYAR LUNAS");
                    cBayar.setSelectedIndex(0);
                    bBayar.setVisible(false);
                    bBayCetk.setVisible(false);
                }
            }

        }

    }//GEN-LAST:event_cBayarActionPerformed

    private void tNomBayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNomBayKeyReleased
        String nominal = tNomBay.getText().replaceAll("[^\\d]", "");
        double Rp = Double.parseDouble(nominal);
        DecimalFormat df = new DecimalFormat("#,###,###");
        tNomBay.setText(df.format(Rp));

        int bayar = Integer.parseInt(tNomBay.getText().replace(".", ""));
        int harga = Integer.parseInt(lblHarga.getText().replace(".", "").substring(2));
        if (bayar > harga) {
            peringatan.setVisible(true);
            cBayar.setSelectedIndex(0);
            cBayar.setEnabled(false);
        } else {
            peringatan.setVisible(false);
            cBayar.setEnabled(true);
        }
    }//GEN-LAST:event_tNomBayKeyReleased

    private void tNomBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomBayActionPerformed

    }//GEN-LAST:event_tNomBayActionPerformed

    private void cJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJenisActionPerformed
        if (cJenis.getSelectedItem().equals("- Pilih Jenis -")) {
            lblHarga.setText("Rp.0");
        } else if (!cJenis.getSelectedItem().equals("- Pilih Jenis -")) {
            try {
                jenis_pembayaran jp = new jenis_pembayaran();
                jenis_pembayaran.setNama_jenis(cJenis.getSelectedItem().toString());
                jp.Konversi();
                double Rp = Double.parseDouble(String.valueOf(jenis_pembayaran.getNominal()));
                DecimalFormat df = new DecimalFormat("#,###,###");
                lblHarga.setText("Rp." + df.format(Rp));
            } catch (SQLException sQLException) {
            }
        }
    }//GEN-LAST:event_cJenisActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed

    }//GEN-LAST:event_bResetActionPerformed

    private void bBayCetkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayCetkActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tbPembayaran.getModel();

            // Ambil jumlah baris dalam tabel
            int rowCount = model.getRowCount();

            // Perulangan untuk membaca setiap baris
            for (int i = 0; i < rowCount; i++) {
                // Ambil data dari setiap kolom di baris ke-i
                String nim = model.getValueAt(i, 0).toString();    // Kolom 0
                String nama = model.getValueAt(i, 1).toString();   // Kolom 1
                String angkatan = model.getValueAt(i, 2).toString();     // Kolom 2
                String prodi = model.getValueAt(i, 3).toString();  // Kolom 3

                mahasiswa.setNim(nim);
                mahasiswa.setNama(nama);
                mahasiswa.setAngkatan(Integer.parseInt(angkatan));
                mahasiswa.setProdi(prodi);

                jenis_pembayaran jp = new jenis_pembayaran();
                jenis_pembayaran.setNama_jenis(cJenis.getSelectedItem().toString());
                ResultSet Data = jp.Konversi2();
                Pembayaran pem = new Pembayaran();
                Pembayaran.setNim(nim);
                if (Data.next()) {
                    String bayar = tNomBay.getText().replace(".", "");
                    Pembayaran.setId_pembayaran(tID.getText());
                    Pembayaran.setId_jenis(Data.getString("id_jenis"));
                    Pembayaran.setNominal_pembayaran(Integer.parseInt(bayar));
                    if (!tKeterangan.equals(null)) {
                        Pembayaran.setKeterangan(tKeterangan.getText());
                    } else {
                        Pembayaran.setKeterangan(null);
                    }

                    if (cBayar.getSelectedItem().equals("LUNAS")) {
                        Pembayaran.setStatus(1);
                    } else if (cBayar.getSelectedItem().equals("CICIL")) {
                        Pembayaran.setStatus(2);
                    }
                    pem.tambahPemUt();
                    Print();

                    pb_sementara pbn = new pb_sementara();
                    pbn.hapus();
                    getData();
                    autoID();

                }
            }

        } catch (SQLException sQLException) {
        }
        JOptionPane.showMessageDialog(null, "PEMBAYARAN SELESAI");
        pnKonten.removeAll();
        pnKonten.add(new History());
        pnKonten.repaint();
        pnKonten.revalidate();
    }//GEN-LAST:event_bBayCetkActionPerformed

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tbPembayaran.getModel();

            // Ambil jumlah baris dalam tabel
            int rowCount = model.getRowCount();

            // Perulangan untuk membaca setiap baris
            for (int i = 0; i < rowCount; i++) {
                // Ambil data dari setiap kolom di baris ke-i
                String nim = model.getValueAt(i, 0).toString();    // Kolom 0
                String nama = model.getValueAt(i, 1).toString();   // Kolom 1
                String angkatan = model.getValueAt(i, 2).toString();     // Kolom 2
                String prodi = model.getValueAt(i, 3).toString();  // Kolom 3

                mahasiswa.setNim(nim);
                mahasiswa.setNama(nama);
                mahasiswa.setAngkatan(Integer.parseInt(angkatan));
                mahasiswa.setProdi(prodi);

                jenis_pembayaran jp = new jenis_pembayaran();
                jenis_pembayaran.setNama_jenis(cJenis.getSelectedItem().toString());
                ResultSet Data = jp.Konversi2();
                Pembayaran pem = new Pembayaran();
                Pembayaran.setNim(nim);
                if (Data.next()) {
                    String bayar = tNomBay.getText().replace(".", "");
                    Pembayaran.setId_pembayaran(tID.getText());
                    Pembayaran.setId_jenis(Data.getString("id_jenis"));
                    Pembayaran.setNominal_pembayaran(Integer.parseInt(bayar));
                    if (!tKeterangan.equals(null)) {
                        Pembayaran.setKeterangan(tKeterangan.getText());
                    } else {
                        Pembayaran.setKeterangan(null);
                    }

                    if (cBayar.getSelectedItem().equals("LUNAS")) {
                        Pembayaran.setStatus(1);
                    } else if (cBayar.getSelectedItem().equals("CICIL")) {
                        Pembayaran.setStatus(2);
                    }
                    pem.tambahPemUt();
                    pb_sementara pbn = new pb_sementara();
                    pbn.hapus();
                    getData();
                    autoID();

                }
            }

        } catch (SQLException sQLException) {
        }
        JOptionPane.showMessageDialog(null, "PEMBAYARAN BERHASIL");
        pnKonten.removeAll();
        pnKonten.add(new History());
        pnKonten.repaint();
        pnKonten.revalidate();
    }//GEN-LAST:event_bBayarActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        boolean closable = true;
        PopMahasiswa mhs = new PopMahasiswa(null, closable);
        mhs.setVisible(true);
    }//GEN-LAST:event_bTambahActionPerformed

    private void bTambahJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahJenisActionPerformed
        boolean closable = true;
        TambahJenis2 mhs = new TambahJenis2(null, closable);
        mhs.setVisible(true);
        for (int i = cJenis.getItemCount() - 1; i >= 0; i--) {
            if (!cJenis.getItemAt(i).equals("- Pilih Jenis -")) {
                cJenis.removeItemAt(i);
            }
        }
        cJenis();
    }//GEN-LAST:event_bTambahJenisActionPerformed

    private void tbPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPembayaranMouseClicked
        bReset.setText("HAPUS");
    }//GEN-LAST:event_tbPembayaranMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed

    }//GEN-LAST:event_jPanel1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBayCetk;
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bTambahJenis;
    private javax.swing.JComboBox<String> cBayar;
    private javax.swing.JComboBox<String> cJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel peringatan;
    private javax.swing.JPanel pnKuitansi;
    private javax.swing.JLabel tAngkatan;
    private javax.swing.JLabel tAngkatan2;
    private javax.swing.JLabel tID;
    private javax.swing.JLabel tJumlah;
    private javax.swing.JLabel tJumlah2;
    private javax.swing.JTextField tKeterangan;
    private javax.swing.JLabel tKeterangann;
    private javax.swing.JLabel tNamJen;
    private javax.swing.JLabel tNamJen2;
    private javax.swing.JLabel tNama1;
    private javax.swing.JLabel tNama2;
    private javax.swing.JLabel tNim;
    private javax.swing.JLabel tNim2;
    private javax.swing.JTextField tNomBay;
    private javax.swing.JLabel tProdi;
    private javax.swing.JLabel tProdi2;
    private javax.swing.JLabel tTanggal;
    private javax.swing.JLabel tTanggal2;
    private javax.swing.JTable tbPembayaran;
    // End of variables declaration//GEN-END:variables
void getData() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("");
        model.addColumn("");
        model.addColumn("");
        model.addColumn("");
        try {
            pb_sementara pem = new pb_sementara();
            ResultSet data = pem.tampil();

            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("NIM"),
                    data.getString("NAMA"),
                    data.getInt("ANGKATAN"),
                    data.getString("PRODI")
                });

            }
        } catch (SQLException sQLException) {
        }
        tbPembayaran.setModel(model);
    }

    void cJenis() {
        try {
            jenis_pembayaran jp = new jenis_pembayaran();
            ResultSet data = jp.tampilComBox();

            while (data.next()) {
                String isi = data.getString("nama_jenis");
                cJenis.addItem(isi);
            }
        } catch (SQLException sQLException) {
        }
    }

    void autoID() {
        String lastId = null;
        String ID = null;

        try {
            Pembayaran pem = new Pembayaran();
            ResultSet data = pem.autoID();

            if (data.next()) {
                lastId = data.getString("id_pembayaran");
            }

            String tahun = new SimpleDateFormat("yyyy").format(new Date());
            if (lastId == null || !lastId.startsWith("ITM" + tahun)) {
                ID = String.format("ITM%s%04d", tahun, 1);
            } else {
                // Ekstrak nomor urut dari ID terakhir
                int idAkhir = Integer.parseInt(lastId.substring(7)); // Ambil bagian urutan
                ID = String.format("ITM%s%04d", tahun, idAkhir + 1);
            }

            tID.setText(ID);

        } catch (SQLException sQLException) {
        }
    }

        void reset() {
            if (bReset.getText().equals("RESET")) {
                try {
                    pb_sementara pbn = new pb_sementara();
                    pbn.hapus();
                } catch (SQLException sQLException) {
                }
                getData();
            } else if (bReset.getText().equals("HAPUS")) {
                int row = tbPembayaran.getSelectedRow();
                String nim = tbPembayaran.getValueAt(row, 0).toString();

                try {
                    pb_sementara pns = new pb_sementara();
                    pns.setNim(nim);
                    pns.hapus1();
                } catch (SQLException ex) {

                }

            }
        }

    void Print() {

        tNama1.setText(mahasiswa.getNama());
        tNama2.setText(mahasiswa.getNama());
        tNim.setText(mahasiswa.getNim());
        tNim2.setText(mahasiswa.getNim());
        tProdi.setText(mahasiswa.getProdi());
        tProdi2.setText(mahasiswa.getProdi());
        tAngkatan.setText(String.valueOf(mahasiswa.getAngkatan()));
        tAngkatan2.setText(String.valueOf(mahasiswa.getAngkatan()));
        tNamJen.setText(cJenis.getSelectedItem().toString());
        tNamJen2.setText(cJenis.getSelectedItem().toString());
        tJumlah.setText("Rp." + tNomBay.getText());
        tJumlah2.setText("Rp." + tNomBay.getText());
        tKeterangann.setText(tKeterangan.getText());
        jLabel50.setText(tKeterangan.getText());
        tTanggal.setText(new SimpleDateFormat("dd - MM - yyyy").format(new Date()));
        tTanggal2.setText(new SimpleDateFormat("dd - MM - yyyy").format(new Date()));

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Laporan");

// Set Page Format dan Orientasi
        PageFormat pf = job.defaultPage();
        pf.setOrientation(PageFormat.LANDSCAPE); // Orientasi Landscape

// Set Printable
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE; // Tidak ada halaman lain
                }

                // Konversi Graphics ke Graphics2D
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY()); // Posisi cetak awal
                g2.scale(0.80, 0.80); // Skala cetak

                try {
                    pnKuitansi.print(g2); // Cetak komponen UI
                } catch (Exception e) {
                    e.printStackTrace();
                    return Printable.NO_SUCH_PAGE;
                }

                return Printable.PAGE_EXISTS;
            }
        });

// Dialog Cetak
        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print(); // Proses cetak
            } catch (PrinterException ex) {
                System.out.println("Gagal mencetak: " + ex.getMessage());
                ex.printStackTrace();
            }
        }

    }
}

//Warna
//18,84,136
//
//42,147,213
//
//55,202,236
//
//61,217,214
//
//173,217,216
