/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pembayaran;

import Pembayaran.Kelas.Pembayaran;
import Pembayaran.Kelas.jenis_pembayaran;
//import static UI.MenuMain.pnUtatma;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SayMukhlisin
 */
public class pnJenisTampil extends javax.swing.JPanel {

    /**
     * Creates new form pnJenisTampil
     */
    public pnJenisTampil() {
        initComponents();
        getData();
         bHapus.setVisible(false);
    }

    void getData() {

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAMA JENIS PEMBAYARAN");
        model.addColumn("NOMINAL");

        try {
            jenis_pembayaran pem = new jenis_pembayaran();
            ResultSet data = pem.tampilJenis();

            while (data.next()) {
                String nominal = String.valueOf(data.getInt("nominal")).replaceAll("[^\\d]", "");
                double nom = Double.parseDouble(nominal);
                DecimalFormat df = new DecimalFormat("#,###,###");
                String nominall = df.format(nom);
                model.addRow(new Object[]{
                    data.getString("id_jenis"),
                    data.getString("nama_jenis"),
                    nominall
                });

            }
        } catch (SQLException sQLException) {
        }
        tbJenis.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbJenis = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bHapus = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tbJenis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJenisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbJenis);

        jLabel2.setFont(new java.awt.Font("DM Sans SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("Jenis Pembayaran");

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bTambah)
                .addGap(18, 18, 18)
                .addComponent(bHapus)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHapus)
                    .addComponent(bTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
     if (bTambah.getText().equals("Tambah")) {
            boolean closable = true;
            popTambahJenis mhs = new popTambahJenis(null, closable);
            mhs.setVisible(true);
        } else if (bTambah.getText().equals("Update")) {
            int row = tbJenis.getSelectedRow();
            jenis_pembayaran.setId_jenis(tbJenis.getModel().getValueAt(row, 0).toString());
            jenis_pembayaran.setNama_jenis(tbJenis.getModel().getValueAt(row, 1).toString());
            jenis_pembayaran.setNominal(Integer.parseInt(tbJenis.getModel().getValueAt(row, 2).toString().replace(",", "")));
            boolean closable = true;
            popUpdateJenis mhs = new popUpdateJenis(null, closable);
            mhs.setVisible(true);
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
 int row = tbJenis.getSelectedRow();
        String id = tbJenis.getModel().getValueAt(row, 0).toString();
        jenis_pembayaran.setId_jenis(id);
        try {
            jenis_pembayaran jp = new jenis_pembayaran();
            jp.hapusJenis();
        } catch (SQLException sQLException) {
        }
//        pnUtatma.removeAll();
//        pnUtatma.add(new pnJenisTampil());
//        pnUtatma.repaint();
//        pnUtatma.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed

    private void tbJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJenisMouseClicked
       bHapus.setVisible(true);
       bTambah.setText("Update");// TODO add your handling code here:
    }//GEN-LAST:event_tbJenisMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbJenis;
    // End of variables declaration//GEN-END:variables
}
