/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pembayaran;

import Pembayaran.Kelas.Pembayaran;
import Pembayaran.Kelas.jenis_pembayaran;
import Pembayaran.Kelas.mahasiswa;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.DecimalFormat;

/**
 *
 * @author Nrl
 */
public class pnTagihan extends javax.swing.JPanel {

    /**
     * Creates new form pembayarannn
     */
    public pnTagihan() {
        initComponents();
        bBayarC.setVisible(false);
        getData2();
    }
    void getData2() {
        tNIM.setText(Pembayaran.getNim());
        tJudul.setText("Pembayaran " + mahasiswa.getNama());

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Pembayaran");
        model.addColumn("Nominal Dibayar");
        model.addColumn("Nominal");
        model.addColumn("Status");
        model.addColumn("Keterangan");

        try {
            Pembayaran pem = new Pembayaran();
            ResultSet data = pem.tampilUt();

            while (data.next()) {
                String bayar = String.valueOf(data.getInt("Nominal Dibayar")).replaceAll("[^\\d]", "");
                String nominal = String.valueOf(data.getInt("Nominal")).replaceAll("[^\\d]", "");
                double nombar = Double.parseDouble(bayar);
                double nom = Double.parseDouble(nominal);
                DecimalFormat df = new DecimalFormat("#,###,###");
                String nominalBayar = df.format(nombar);
                String nominall = (df.format(nom));
                model.addRow(new Object[]{
                    data.getString("ID Pembayaran"),
                    data.getString("Nama Jenis"),
                    nominalBayar,
                    nominall,
                    data.getString("Status"),
                    data.getString("Keterangan")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tbTagihan.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTagihan = new javax.swing.JTable();
        tNIM = new javax.swing.JLabel();
        tJudul = new javax.swing.JLabel();
        bBayar = new javax.swing.JButton();
        bBayarC = new javax.swing.JButton();
        bBalik = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tbTagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTagihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTagihanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTagihan);

        tNIM.setFont(new java.awt.Font("DM Sans", 0, 18)); // NOI18N
        tNIM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tNIM.setText("202357201036");

        tJudul.setFont(new java.awt.Font("DM Sans SemiBold", 0, 24)); // NOI18N
        tJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJudul.setText("Pembayaran Nama Mahasiswa");

        bBayar.setText("Tambah Pembayaran");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });

        bBayarC.setText("Bayar Cicilan");
        bBayarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarCActionPerformed(evt);
            }
        });

        bBalik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bBalik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/KEMBAL GRAY.png"))); // NOI18N
        bBalik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBalik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBalikMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBalik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBayarC, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBayar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
                    .addComponent(tJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tNIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBalik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(tJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNIM)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBayarC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
        mahasiswa.setNama(tJudul.getText().substring(11));
        Pembayaran.setNim(tNIM.getText());
        mahasiswa mhs = new mahasiswa();
        mhs.getMahasiswa();
        if (mahasiswa.getKoneksi().equals("true")) {
            DashPem.Content.removeAll();
            DashPem.Content.add(new pnBayar());
            DashPem.Content.repaint();
            DashPem.Content.revalidate();
        } else if (mahasiswa.getKoneksi().equals("false")) {
            DashPem.Content.removeAll();
            DashPem.Content.add(new pnNoSignal());
            DashPem.Content.repaint();
            DashPem.Content.revalidate();
        }
    }//GEN-LAST:event_bBayarActionPerformed

    private void tbTagihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTagihanMouseClicked
        int row = tbTagihan.getSelectedRow();
        String status = tbTagihan.getModel().getValueAt(row, 4).toString();

        if (status.equals("BELUM LUNAS")) {
            bBayarC.setVisible(true);
        }
    }//GEN-LAST:event_tbTagihanMouseClicked

    private void bBayarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarCActionPerformed
       int row = tbTagihan.getSelectedRow();
        int hargaAsli = Integer.parseInt(tbTagihan.getModel().getValueAt(row, 3).toString().replace(",", ""));
        int hargaCicil = Integer.parseInt(tbTagihan.getModel().getValueAt(row, 2).toString().replace(",", ""));
        int hargaKurang = hargaAsli - hargaCicil;
        Pembayaran.setNominal_pembayaran(hargaKurang);
        Pembayaran.setNominal_jenis(hargaAsli);
        jenis_pembayaran.setNama_jenis(tbTagihan.getModel().getValueAt(row, 1).toString());
        Pembayaran.setId_pembayaran(tbTagihan.getModel().getValueAt(row, 0).toString());
        mahasiswa mhs = new mahasiswa();
        mhs.getMahasiswa();
        if (mahasiswa.getKoneksi().equals("true")) {
            DashPem.Content.removeAll();
            DashPem.Content.add(new pnCicilan());
            DashPem.Content.repaint();
            DashPem.Content.revalidate();
        } else if (mahasiswa.getKoneksi().equals("false")) {
            DashPem.Content.removeAll();
            DashPem.Content.add(new pnNoSignal());
            DashPem.Content.repaint();
            DashPem.Content.revalidate();
        }
    }//GEN-LAST:event_bBayarCActionPerformed

    private void bBalikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBalikMouseClicked
        mahasiswa mhs = new mahasiswa();
        mhs.getMahasiswa();
        if (mahasiswa.getKoneksi().equals("true")) {
            DashPem.Content.removeAll();
            DashPem.Content.add(new Mahasiswa());
            DashPem.Content.repaint();
            DashPem.Content.revalidate();
        } else if (mahasiswa.getKoneksi().equals("false")) {
            DashPem.Content.removeAll();
            DashPem.Content.add(new pnNoSignal());
            DashPem.Content.repaint();
            DashPem.Content.revalidate();
        }
    }//GEN-LAST:event_bBalikMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bBalik;
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bBayarC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tJudul;
    private javax.swing.JLabel tNIM;
    private javax.swing.JTable tbTagihan;
    // End of variables declaration//GEN-END:variables
}
