/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pembayaran;

import Pembayaran.template.*;
import Pembayaran.Kelas.Pembayaran;
import Pembayaran.Kelas.jenis_pembayaran;
import Pembayaran.Kelas.mahasiswa;
//import static UI.MenuMain.pnUtatma;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.DecimalFormat;

/**
 *
 * @author Nrl
 */
public class pnTagihan extends javax.swing.JPanel {

    /**
     * Creates new form pembayarannn
     */
    public pnTagihan() {
        initComponents();
        bBayarC.setVisible(false);
        getData2();
    }
    void getData2() {
        tNIM.setText(Pembayaran.getNim());
        tJudul.setText("Pembayaran " + mahasiswa.getNama());

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Pembayaran");
        model.addColumn("Nominal Dibayar");
        model.addColumn("Nominal");
        model.addColumn("Status");
        model.addColumn("Keterangan");

        try {
            Pembayaran pem = new Pembayaran();
            ResultSet data = pem.tampilUt();

            while (data.next()) {
                String bayar = String.valueOf(data.getInt("Nominal Dibayar")).replaceAll("[^\\d]", "");
                String nominal = String.valueOf(data.getInt("Nominal")).replaceAll("[^\\d]", "");
                double nombar = Double.parseDouble(bayar);
                double nom = Double.parseDouble(nominal);
                DecimalFormat df = new DecimalFormat("#,###,###");
                String nominalBayar = df.format(nombar);
                String nominall = (df.format(nom));
                model.addRow(new Object[]{
                    data.getString("ID Pembayaran"),
                    data.getString("Nama Jenis"),
                    nominalBayar,
                    nominall,
                    data.getString("Status"),
                    data.getString("Keterangan")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tbTagihan.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTagihan = new javax.swing.JTable();
        tNIM = new javax.swing.JLabel();
        tJudul = new javax.swing.JLabel();
        bBayar = new javax.swing.JButton();
        bBayarC = new javax.swing.JButton();
        bBalik = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tbTagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTagihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTagihanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTagihan);

        tNIM.setFont(new java.awt.Font("DM Sans", 0, 18)); // NOI18N
        tNIM.setText("202357201036");

        tJudul.setFont(new java.awt.Font("DM Sans SemiBold", 0, 24)); // NOI18N
        tJudul.setText("Pembayaran Nama Mahasiswa");

        bBayar.setText("Tambah Pembayaran");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });

        bBayarC.setText("Bayar Cicilan");
        bBayarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarCActionPerformed(evt);
            }
        });

        bBalik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bBalik.setText("<---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tNIM)
                        .addGap(513, 513, 513))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tJudul)
                        .addGap(397, 397, 397))))
            .addGroup(layout.createSequentialGroup()
                .addGap(838, 838, 838)
                .addComponent(bBayarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBayar)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBalik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBalik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(tJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNIM)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBayar)
                    .addComponent(bBayarC))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
        mahasiswa.setNama(tJudul.getText().substring(11));
        Pembayaran.setNim(tNIM.getText());
//        pnUtatma.removeAll();
//        pnUtatma.add(new pnBayar());
//        pnUtatma.repaint();
//        pnUtatma.revalidate();
    }//GEN-LAST:event_bBayarActionPerformed

    private void tbTagihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTagihanMouseClicked
        int row = tbTagihan.getSelectedRow();
        String status = tbTagihan.getModel().getValueAt(row, 4).toString();

        if (status.equals("BELUM LUNAS")) {
            bBayarC.setVisible(true);
        }
    }//GEN-LAST:event_tbTagihanMouseClicked

    private void bBayarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarCActionPerformed
       int row = tbTagihan.getSelectedRow();
        int hargaAsli = Integer.parseInt(tbTagihan.getModel().getValueAt(row, 3).toString().replace(",", ""));
        int hargaCicil = Integer.parseInt(tbTagihan.getModel().getValueAt(row, 2).toString().replace(",", ""));
        int hargaKurang = hargaAsli - hargaCicil;
        Pembayaran.setNominal_pembayaran(hargaKurang);
        Pembayaran.setNominal_jenis(hargaAsli);
        jenis_pembayaran.setNama_jenis(tbTagihan.getModel().getValueAt(row, 1).toString());
        Pembayaran.setId_pembayaran(tbTagihan.getModel().getValueAt(row, 0).toString());
//        pnUtatma.removeAll();
//        pnUtatma.add(new pnCicilan());
//        pnUtatma.repaint();
//        pnUtatma.revalidate();
    }//GEN-LAST:event_bBayarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bBalik;
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bBayarC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tJudul;
    private javax.swing.JLabel tNIM;
    private javax.swing.JTable tbTagihan;
    // End of variables declaration//GEN-END:variables
}
