/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Perpustakaan.popUp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Perpustakaan.KELAS.Anggota;
import Perpustakaan.FRAME.menuAnggota;
import Perpustakaan.FRAME.menuKategori;
import static Perpustakaan.FRAME.menuUtama.pnUtama;
import static Perpustakaan.popUp.PopUp_Anggota.lb_Id;
/**
 *
 * @author WINDOWS 10
 */
public class PopUp_Anggota extends javax.swing.JFrame {

    /**
     * Creates new form PopUp_Anggota
     */
    public PopUp_Anggota() throws SQLException {
        initComponents();
        autoId();
    }
    
    void reset() {
        tNama.setText(null);
        tAlamat.setText(null);
        tNoHp.setText(null);
        tEmail.setText(null);
        tNim.setText(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        bHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bKembali = new javax.swing.JButton();
        tNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        tNoHp = new javax.swing.JTextField();
        tNim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        lb_Id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("EMAILL");

        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/bin.png"))); // NOI18N
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NO HP");

        bKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/back.png"))); // NOI18N
        bKembali.setText("KEMBALI");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NAMA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ALAMAT");

        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/diskette.png"))); // NOI18N
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("NIM");

        lb_Id.setBackground(new java.awt.Color(102, 204, 255));
        lb_Id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_Id.setForeground(new java.awt.Color(102, 204, 255));
        lb_Id.setText("ANGGOTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lb_Id))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(bSimpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bHapus)
                                    .addGap(18, 18, 18)
                                    .addComponent(bKembali))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tNoHp)
                                        .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tNama)
                                        .addComponent(tEmail)
                                        .addComponent(tNim, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Id)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(57, 57, 57))
                            .addComponent(tNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(tNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bKembali)
                    .addComponent(bHapus))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        try {
        Anggota ang = new Anggota();

        // Validasi ID Anggota
        if (lb_Id.getText().isEmpty() || !lb_Id.getText().matches("\\d+")) {
        throw new IllegalArgumentException("NIM harus berupa angka dan tidak boleh kosong.");
        }
        ang.setIdAnggota(Integer.parseInt(lb_Id.getText()));

        // Validasi Nama
        if (tNama.getText().isEmpty() || !tNama.getText().matches("[a-zA-Z\\s]+") || tNama.getText().length() < 3) {
        throw new IllegalArgumentException("Nama hanya boleh berisi huruf, tidak boleh kosong, dan harus memiliki minimal 3 karakter.");
        }
        ang.setNama(tNama.getText());

        // Validasi Alamat
        if (tAlamat.getText().isEmpty()) {
        throw new IllegalArgumentException("Alamat tidak boleh kosong.");
        }
        ang.setAlamat(tAlamat.getText());

        // Validasi Nomor HP
        if (tNoHp.getText().isEmpty() || !tNoHp.getText().matches("\\d{10,13}")) {
        throw new IllegalArgumentException("Nomor HP harus berupa angka, tidak boleh mengandung huruf, dan memiliki 10-13 digit.");
        }
        ang.setNoHp(tNoHp.getText());

        // Validasi Email
        if (tEmail.getText().isEmpty() || !tEmail.getText().matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
        throw new IllegalArgumentException("Email tidak valid atau kosong.");
        }
        ang.setEmail(tEmail.getText());

        // Validasi NIM/NIDN
        if (tNim.getText().isEmpty() || !tNim.getText().matches("\\d{5,16}")) {
        throw new IllegalArgumentException("NIM/NIDN harus berupa angka, tidak boleh huruf, memiliki 5-16 digit, dan tidak boleh kosong.");
        }
        ang.setNim(tNim.getText());

        // Tambahkan data anggota ke database
        ang.tambahAnggota();
        System.out.println("Data berhasil disimpan!");

        // Reset form
        reset();
    
         // Menyimpan data kategori ke database;
        reset(); // Mereset form setelah penyimpanan
        autoId(); // Mengatur ulang ID kategori otomatis
        
        pnUtama.removeAll();
        pnUtama.add(new menuAnggota());
        pnUtama.repaint();
        pnUtama.revalidate();
    
        } catch (IllegalArgumentException e) {
        // Tampilkan pesan error validasi
        javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "Validasi Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
    }    catch (SQLException sQLException) {
    // Tangani error SQL
    javax.swing.JOptionPane.showMessageDialog(null, "Data tidak masuk ke database. Periksa koneksi atau data!", "Kesalahan Database", javax.swing.JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_bSimpanActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        try {
        // Validasi ID
        if (lb_Id.getText().isEmpty() || !lb_Id.getText().matches("\\d+")) {
            throw new IllegalArgumentException("ID Anggota tidak valid. Pastikan ID berupa angka dan tidak kosong.");
        }

        // Konfirmasi sebelum menghapus
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", 
                                                    "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Hapus data
            Anggota cty = new Anggota();
            cty.setIdAnggota(Integer.parseInt(lb_Id.getText()));
            cty.hapusAnggota();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);

            // Reset form setelah penghapusan
            reset();
            
            pnUtama.removeAll();
        pnUtama.add(new menuAnggota());
        pnUtama.repaint();
        pnUtama.revalidate();
        }
    } catch (IllegalArgumentException e) {
        // Tampilkan pesan error validasi
        JOptionPane.showMessageDialog(null, e.getMessage(), "Validasi Gagal", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException sQLException) {
        // Tampilkan pesan error SQL
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghapus data. Periksa koneksi atau data Anda!", 
                                      "Kesalahan Database", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PopUp_Anggota().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PopUp_Anggota.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKembali;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lb_Id;
    public static javax.swing.JTextField tAlamat;
    public static javax.swing.JTextField tEmail;
    public static javax.swing.JTextField tNama;
    public static javax.swing.JTextField tNim;
    public static javax.swing.JTextField tNoHp;
    // End of variables declaration//GEN-END:variables
private void autoId() throws SQLException {
        Anggota auto = new Anggota();
        int newID = auto.autoId();
        lb_Id.setText(String.valueOf(newID));
    }

}

