/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Perpustakaan.popUp;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Perpustakaan.KELAS.Item;
import Perpustakaan.KELAS.Lemari;
import Perpustakaan.FRAME.menuAnggota;
import Perpustakaan.FRAME.menuItem;
import static Perpustakaan.FRAME.menuItem.tItem;
import Perpustakaan.FRAME.menuLemari;
import static Perpustakaan.FRAME.menuUtama.pnUtama;
import static Perpustakaan.popUp.PopUp_Lemari.Lb_lem;
import static Perpustakaan.popUp.PopUp_Lemari.tLemari;
import static Perpustakaan.popUp.PopUp_Lemari.tRak;
import static Perpustakaan.popUp.PopUp_Lemari.tJudul;
import static Perpustakaan.popUp.PopUp_Lemari.tTahunTerbit;
import static Perpustakaan.popUp.PopUp_Lemari.tJumlah;


/**
 *
 * @author WINDOWS 10
 */
public class PopUp_Lemari extends javax.swing.JFrame {

    /**
     * Creates new form PopUp_Lemari
     */
    public PopUp_Lemari() throws SQLException {
        initComponents();
        autoId();
        loadTable();
    }
    
    void reset() {
        tLemari.setText(null);
        tRak.setText(null);
    }
    
    private void autoId() throws SQLException {
        Lemari auto = new Lemari();
        int newID = auto.autoId();
        Lb_lem.setText(String.valueOf(newID));
    }
     private void loadTable() {
        // Inisialisasi model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Item");
        model.addColumn("Kategori");
        model.addColumn("Lemari");
        model.addColumn("Judul");
        model.addColumn("Penulis");
        model.addColumn("Tahun Terbit");
        model.addColumn("Jumlah");
        model.addColumn("File");

        try {
            Item itemHandler = new Item();
            ResultSet resultSet = itemHandler.tampilItem();

            // Iterasi hasil query dan tambahkan ke model tabel
            while (resultSet.next()) {
                model.addRow(new Object[] {
                    resultSet.getInt("id_item"),
                    resultSet.getString("nama_kategori"),
                    resultSet.getString("lemari"),
                    resultSet.getString("nama_barang"),
                    resultSet.getString("penulis"),
                    resultSet.getInt("tahun_terbit"),
                    resultSet.getInt("jumlah"),
                    resultSet.getString("file")
                });
            }
        } catch (SQLException e) {
            Logger.getLogger(menuItem.class.getName()).log(Level.SEVERE, "Error loading table data", e);
        }

        // Set model ke tabel
        tItem.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tLemari = new javax.swing.JTextField();
        tRak = new javax.swing.JTextField();
        bHapus = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bKembali = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Lb_lem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tJudul = new javax.swing.JTextField();
        tJumlah = new javax.swing.JTextField();
        tTahunTerbit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tItem = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lemari");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Rak");

        tLemari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLemariActionPerformed(evt);
            }
        });

        tRak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRakActionPerformed(evt);
            }
        });

        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/bin.png"))); // NOI18N
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/diskette.png"))); // NOI18N
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/back.png"))); // NOI18N
        bKembali.setText("KEMBALI");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/refresh.png"))); // NOI18N
        jButton4.setText("UBAH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Lb_lem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lb_lem.setText("LEMARI");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Judul");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Jumlah");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tahun Terbit");

        tJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJudulActionPerformed(evt);
            }
        });

        tJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJumlahActionPerformed(evt);
            }
        });

        tTahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTahunTerbitActionPerformed(evt);
            }
        });

        tItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tItem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lb_lem)
                        .addGap(820, 820, 820))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addComponent(bSimpan, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tRak)
                                            .addComponent(tLemari)
                                            .addComponent(tJudul)
                                            .addComponent(tJumlah)
                                            .addComponent(tTahunTerbit)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(bHapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(bKembali)))))
                        .addGap(439, 439, 439))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Lb_lem)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tLemari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bKembali)
                    .addComponent(bHapus)
                    .addComponent(jButton4)
                    .addComponent(bSimpan))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tLemariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLemariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLemariActionPerformed

    private void tRakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRakActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        try {
            Lemari lm = new Lemari();
            lm.setId_lemari((Lb_lem.getText()));
            lm.hapusLemari();
        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        try {
            Lemari lmr = new Lemari();
            lmr.setId_lemari(Lb_lem.getText());
            lmr.setLemari(tLemari.getText());
            lmr.setRak(tRak.getText());
            lmr.setJudul(tJudul.getText());
            lmr.setJumlah(tJumlah.getText());
            lmr.setTahun_terbit(tTahunTerbit.getText());
            
            lmr.tambahLemari();// Menyimpan data kategori ke database;
            reset(); // Mereset form setel ah penyimpanan
            autoId(); // Mengatur ulang ID kategori otomatis
        
            pnUtama.removeAll();
            pnUtama.add(new menuLemari());
            pnUtama.repaint();
            pnUtama.revalidate();
            } catch (SQLException sQLException) {
            System.out.println("Data tidak masuk");
            }
            reset();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            Lemari lm = new Lemari();
            PopUp_Lemari pp = new PopUp_Lemari();
     
            lm.setLemari(tLemari.getText());

            lm.ubahLemari();
        } catch (SQLException sQLException) {
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bKembaliActionPerformed

    private void tJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJudulActionPerformed

    private void tJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJumlahActionPerformed

    private void tTahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTahunTerbitActionPerformed

    private void tItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tItemMouseClicked
    int baris = tItem.getSelectedRow();

    String lemari = tItem.getValueAt(baris, 2).toString();
    String judul = tItem.getValueAt(baris, 3).toString();
    String jumlah = tItem.getValueAt(baris, 6).toString();
    String tahun = tItem.getValueAt(baris, 5).toString();
    
    tJudul.setText(judul);
    tJumlah.setText(jumlah);
    tTahunTerbit.setText(tahun);
    tLemari.setText(lemari);
    }//GEN-LAST:event_tItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp_Lemari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp_Lemari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp_Lemari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp_Lemari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PopUp_Lemari().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PopUp_Lemari.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Lb_lem;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKembali;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tItem;
    public static javax.swing.JTextField tJudul;
    public static javax.swing.JTextField tJumlah;
    public static javax.swing.JTextField tLemari;
    public static javax.swing.JTextField tRak;
    public static javax.swing.JTextField tTahunTerbit;
    // End of variables declaration//GEN-END:variables


    
}
