/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Perpustakaan.popUp;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Perpustakaan.KELAS.Item;
import Perpustakaan.KELAS.Kategori;
import Perpustakaan.FRAME.menuItem;
import static Perpustakaan.FRAME.menuUtama.pnUtama;
import static Perpustakaan.popUp.PopUp_Item1.Lb_item;
import static Perpustakaan.popUp.PopUp_Item1.tJumlah;
import static Perpustakaan.popUp.PopUp_Item1.cKategori;
import static Perpustakaan.popUp.PopUp_Item1.tTahunTerbit;
import static Perpustakaan.popUp.PopUp_Item1.Lb_item;
import static Perpustakaan.popUp.PopUp_Item1.cKategori;
import static Perpustakaan.popUp.PopUp_Item1.tJumlah;
import static Perpustakaan.popUp.PopUp_Item1.tPenulis;
import static Perpustakaan.popUp.PopUp_Item1.tTahunTerbit;


/**
 *
 * @author WINDOWS 10
 */
public class PopUp_Item1 extends javax.swing.JFrame {

    /**
     * Creates new form PopUp_Item
     */
    public PopUp_Item1() throws SQLException {
        initComponents();
        autoId();
        comboCategory();
        tFile.setEnabled(false);
    }
    
    void reset() {
    try {
        autoId(); 
    } catch (SQLException e) {
        e.printStackTrace();
    }
    cKategori.setSelectedIndex(-1); 
    tNamaBarang.setText("");
    tPenulis.setText("");
    tTahunTerbit.setText("");
    tJumlah.setText("");
    tFile.setText("");
    tLemari.setText("");

}
    
    void comboCategory() {
        try {
            Kategori cat = new Kategori();
            ResultSet data = cat.tampilComboBox();

            while (data.next()) {
                String isi = data.getString("nama_kategori");
                cKategori.addItem(isi);
            }

        } catch (SQLException ex) {
            Logger.getLogger(PopUp_Item1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tTahunTerbit = new javax.swing.JTextField();
        tJumlah = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        cKategori = new javax.swing.JComboBox<>();
        Lb_item = new javax.swing.JLabel();
        tPenulis = new javax.swing.JTextField();
        tNamaBarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tFile = new javax.swing.JTextField();
        tUpload = new javax.swing.JButton();
        tLemari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bUbah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Kategori");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Judul");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Penulis");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tahun Terbit");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Jumlah");

        tJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJumlahActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/back.png"))); // NOI18N
        jButton3.setText("KEMBALI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/bin.png"))); // NOI18N
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        cKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKategoriActionPerformed(evt);
            }
        });

        Lb_item.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lb_item.setText("MENU ITEM");

        tNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaBarangActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("File");

        tFile.setEditable(false);

        tUpload.setText("UPLOAD");
        tUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUploadActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Lemari");

        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/refresh.png"))); // NOI18N
        bUbah.setText("UBAH");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bHapus)
                                .addGap(27, 27, 27)
                                .addComponent(jButton3))
                            .addComponent(tLemari)
                            .addComponent(tJumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tNamaBarang)
                            .addComponent(tPenulis)
                            .addComponent(cKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tTahunTerbit)
                            .addComponent(tFile, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(tUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Lb_item)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Lb_item)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tTahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLemari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tUpload)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(bHapus)
                    .addComponent(bUbah))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJumlahActionPerformed

    private void cKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKategoriActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cKategoriActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        try {
            Item it = new Item();
            it.setIdItem(Integer.parseInt(Lb_item.getText()));
            it.hapusItem();
            
            reset();
    autoId();

    pnUtama.removeAll();
    pnUtama.add(new menuItem());
    pnUtama.repaint();
    pnUtama.revalidate();
        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUploadActionPerformed
        // TODO add your handling code here:
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();

    javax.swing.filechooser.FileNameExtensionFilter filter = new javax.swing.filechooser.FileNameExtensionFilter("PDF & Images", "pdf", "PPT", "WORD");
    fileChooser.setFileFilter(filter);

    int returnValue = fileChooser.showOpenDialog(this);

    if (returnValue == javax.swing.JFileChooser.APPROVE_OPTION) {        java.io.File selectedFile = fileChooser.getSelectedFile();
        tFile.setText(selectedFile.getAbsolutePath());
    } else {
        JOptionPane.showMessageDialog(this, "Tidak ada file yang dipilih!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_tUploadActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        if (tNamaBarang.getText().trim().isEmpty() ||
    tPenulis.getText().trim().isEmpty() ||
    tTahunTerbit.getText().trim().isEmpty() ||
    tJumlah.getText().trim().isEmpty() ||
    cKategori.getSelectedIndex() == -1 ||
    tLemari.getText().trim().isEmpty()) { // Tambahkan validasi untuk tLemari

    JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

try {
    // Parsing data
    String idItem = Lb_item.getText();
    String namaItem = tNamaBarang.getText().trim();
    String penulis = tPenulis.getText().trim();
    int tahunTerbit = Integer.parseInt(tTahunTerbit.getText().trim());
    int jumlah = Integer.parseInt(tJumlah.getText().trim());
    String kategori = (String) cKategori.getSelectedItem();
    String filePath = tFile.getText().trim();
    String lemari = tLemari.getText().trim(); // Ambil data dari tLemari

    // Membuat objek Item untuk pembaruan
    Item item = new Item();
    item.setIdItem(Integer.parseInt(idItem));
    item.setPenulis(penulis);
    item.setTahunTerbit(tahunTerbit);
    item.setJumlah(jumlah);
    item.setKategori(kategori);
    item.setFile(filePath);
    item.setLemari(lemari); // Set nilai tLemari ke objek Item

    // Update item ke database
    item.ubahItem();

    JOptionPane.showMessageDialog(this, "Data item berhasil diperbarui!", "Informasi", JOptionPane.INFORMATION_MESSAGE);

    // Reset form setelah update
    reset();
    autoId();

    pnUtama.removeAll();
    pnUtama.add(new menuItem());
    pnUtama.repaint();
    pnUtama.revalidate();
    
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Tahun terbit dan jumlah harus berupa angka!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_bUbahActionPerformed

    private void tNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp_Item1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp_Item1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp_Item1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp_Item1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PopUp_Item1().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PopUp_Item1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Lb_item;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bUbah;
    public static javax.swing.JComboBox<String> cKategori;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField tFile;
    public static javax.swing.JTextField tJumlah;
    public static javax.swing.JTextField tLemari;
    public static javax.swing.JTextField tNamaBarang;
    public static javax.swing.JTextField tPenulis;
    public static javax.swing.JTextField tTahunTerbit;
    private javax.swing.JButton tUpload;
    // End of variables declaration//GEN-END:variables
    private void autoId() throws SQLException {
        Item auto = new Item();
        int newID = auto.autoId();
        Lb_item.setText(String.valueOf(newID));
    }

}

