/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pembayaran.Frame;

/**
 *
 * @author SayMukhlisin
 */
public class datadiri extends javax.swing.JPanel {

    /**
     * Creates new form datadiri
     */
    public datadiri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        gradient1 = new pallete.gradient();

        setBackground(new java.awt.Color(51, 0, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("DM Sans SemiBold", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ikon");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 6, 148, 184));

        jLabel3.setFont(new java.awt.Font("DM Sans SemiBold", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nama");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 208, 390, -1));

        jLabel4.setFont(new java.awt.Font("DM Sans SemiBold", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NIM");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 238, 390, -1));

        jLabel6.setFont(new java.awt.Font("DM Sans SemiBold", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pilih Pembayaran");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 287, 390, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 312, 190, -1));

        jLabel7.setFont(new java.awt.Font("DM Sans", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Pembayaran Lain?");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 190, -1));

        jLabel8.setFont(new java.awt.Font("DM Sans SemiBold", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pembayaran Lain");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 374, 390, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 399, 190, -1));

        jLabel9.setFont(new java.awt.Font("DM Sans SemiBold", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nominal");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 439, 390, -1));

        jTextField3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Rp 1.500.000");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 464, 189, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("Tambah");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 516, -1, -1));

        gradient1.setColorStart(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout gradient1Layout = new javax.swing.GroupLayout(gradient1);
        gradient1.setLayout(gradient1Layout);
        gradient1Layout.setHorizontalGroup(
            gradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        gradient1Layout.setVerticalGroup(
            gradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        add(gradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pallete.gradient gradient1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
