/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author SayMukhlisin
 */
public class contohh extends javax.swing.JFrame {

    /**
     * Creates new form contohh
     */
    public contohh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        KPGBLU = new javax.swing.JLabel();
        KPGGRAY = new javax.swing.JLabel();
        BUKUBLU = new javax.swing.JLabel();
        BUKUGRAY = new javax.swing.JLabel();
        PEMBABLU = new javax.swing.JLabel();
        PEMBAGRAY1 = new javax.swing.JLabel();
        IVEBLU = new javax.swing.JLabel();
        IVEGRAY = new javax.swing.JLabel();
        MANABLU = new javax.swing.JLabel();
        MANAGRAY = new javax.swing.JLabel();
        PERPUSBLU = new javax.swing.JLabel();
        PERPUSGRAY = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LOGOUTBLU = new javax.swing.JLabel();
        LOGOUTGRAY = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/User New.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("DM Sans SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Admin");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("DM Sans SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("24 November 2024");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        KPGBLU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KPGBLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/KEPEGAWAIAN BLU.png"))); // NOI18N
        jPanel1.add(KPGBLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 128, 99, -1));

        KPGGRAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KPGGRAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/KEPEGAWAIAN GRAY.png"))); // NOI18N
        jPanel1.add(KPGGRAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 128, 99, -1));

        BUKUBLU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BUKUBLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/BUKU INDUK BLUEpng.png"))); // NOI18N
        jPanel1.add(BUKUBLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 128, 98, -1));

        BUKUGRAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BUKUGRAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/BUKU INDUK GRAY.png"))); // NOI18N
        jPanel1.add(BUKUGRAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 128, 98, -1));

        PEMBABLU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PEMBABLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/PEMBAYARAN BLUE.png"))); // NOI18N
        jPanel1.add(PEMBABLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 128, 98, -1));

        PEMBAGRAY1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PEMBAGRAY1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/PEMBAYARAN GRAYpng.png"))); // NOI18N
        jPanel1.add(PEMBAGRAY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 128, 98, -1));

        IVEBLU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IVEBLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/IVENTARISBLU.png"))); // NOI18N
        jPanel1.add(IVEBLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 364, 99, -1));

        IVEGRAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IVEGRAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/IVENTARISGRAY.png"))); // NOI18N
        jPanel1.add(IVEGRAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 364, 99, -1));

        MANABLU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MANABLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/MANAJEMEN BLU.png"))); // NOI18N
        jPanel1.add(MANABLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 150, -1));

        MANAGRAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MANAGRAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/MANAJEMEN GRAY.png"))); // NOI18N
        jPanel1.add(MANAGRAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 150, -1));

        PERPUSBLU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PERPUSBLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/PERPUSTAKAAN BLU.png"))); // NOI18N
        jPanel1.add(PERPUSBLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 364, 110, -1));

        PERPUSGRAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PERPUSGRAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/PERPUSTAKAAN GRAY.png"))); // NOI18N
        jPanel1.add(PERPUSGRAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 364, 110, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGOUTBLU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGOUTBLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/LOGOUT BLU.png"))); // NOI18N
        jPanel3.add(LOGOUTBLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LOGOUTGRAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGOUTGRAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/LOGOUT GRAY.png"))); // NOI18N
        jPanel3.add(LOGOUTGRAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LOGOUT.setFont(new java.awt.Font("DM Sans", 1, 18)); // NOI18N
        LOGOUT.setText("Log Out");
        jPanel3.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 110, 30));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contohh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contohh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contohh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contohh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contohh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BUKUBLU;
    private javax.swing.JLabel BUKUGRAY;
    private javax.swing.JLabel IVEBLU;
    private javax.swing.JLabel IVEGRAY;
    private javax.swing.JLabel KPGBLU;
    private javax.swing.JLabel KPGGRAY;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel LOGOUTBLU;
    private javax.swing.JLabel LOGOUTGRAY;
    private javax.swing.JLabel MANABLU;
    private javax.swing.JLabel MANAGRAY;
    private javax.swing.JLabel PEMBABLU;
    private javax.swing.JLabel PEMBAGRAY1;
    private javax.swing.JLabel PERPUSBLU;
    private javax.swing.JLabel PERPUSGRAY;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
